/**
 * `Cabecera` and the batch.
 *
 * The header is the block that travels in every submission and the one with the fewest official
 * examples; the batch is where the chain stops being a per-record property and becomes an
 * ordering constraint. Both are audited in docs/spec-notes.md §19.
 */
import type { EslabonAltaCanonico } from '@verifactu-js/core';
import { describe, expect, it } from 'vitest';

import {
  type Cabecera,
  type RegistroFactura,
  serializarRemision,
  VerifactuXmlError,
  type VerifactuXmlErrorCode,
} from '../src/index.js';
import {
  altaMinima,
  altaPrevia,
  anulacionMinima,
  CABECERA,
  cadena,
  documento,
  SISTEMA,
} from './helpers/documentos.js';
import { textoDe, todosLosTextosDe } from './helpers/leer.js';
import { esperarInvalido, esperarValido } from './helpers/xsd.js';

function codigoDe(fn: () => unknown): VerifactuXmlErrorCode | 'NO_LANZO' {
  try {
    fn();
  } catch (error) {
    expect(error).toBeInstanceOf(VerifactuXmlError);
    return (error as VerifactuXmlError).code;
  }
  return 'NO_LANZO';
}

/** Builds `cuantos` records that really do chain onto one another. */
async function cadenaDe(cuantos: number): Promise<RegistroFactura[]> {
  const chain = cadena();
  const registros: RegistroFactura[] = [];
  let previous: EslabonAltaCanonico | null = null;

  for (let i = 0; i < cuantos; i += 1) {
    const eslabon: EslabonAltaCanonico = await chain.alta({
      IDEmisorFactura: '89890001K',
      NumSerieFactura: `SERIE/${i}`,
      FechaExpedicionFactura: '01-01-2024',
      TipoFactura: 'F1',
      CuotaTotal: '12.35',
      ImporteTotal: '123.45',
      previous,
    });
    previous = eslabon;

    registros.push({
      eslabon,
      datos: {
        NombreRazonEmisor: 'EMPRESA DE PRUEBA SL',
        DescripcionOperacion: 'PRESTACION DE SERVICIOS',
        Desglose: [
          {
            ClaveRegimen: '01',
            CalificacionOperacion: 'S1',
            TipoImpositivo: '21',
            BaseImponibleOimporteNoSujeto: '111.10',
            CuotaRepercutida: '12.35',
          },
        ],
        SistemaInformatico: SISTEMA,
      },
    });
  }

  return registros;
}

describe('Cabecera', () => {
  it('is written in the SuministroLR namespace, and its children in SuministroInformacion', async () => {
    // The element is declared in SuministroLR.xsd; its type lives in SuministroInformacion.xsd,
    // and the children take their namespace from the type. Name and contents end up in different
    // namespaces (docs/spec-notes.md §19.1).
    const xml = await documento([await altaMinima()]);

    expect(xml).toContain('<sfLR:Cabecera><sf:ObligadoEmision>');
    expect(xml).not.toContain('<sf:Cabecera>');
  });

  it('the wrong prefix is rejected by the XSD, with an error that never says "namespace"', async () => {
    const roto = (await documento([await altaMinima()]))
      .replace('<sfLR:Cabecera>', '<sf:Cabecera>')
      .replace('</sfLR:Cabecera>', '</sf:Cabecera>');

    const errores = await esperarInvalido(roto);
    expect(errores.join(' ')).toContain('Cabecera');
  });

  it('carries the representative when the records were generated by an adviser', async () => {
    const cabecera: Cabecera = {
      ...CABECERA,
      Representante: { NombreRazon: 'ASESORIA SL', NIF: 'B72877814' },
    };
    const xml = await documento([await altaMinima()], cabecera);

    await esperarValido(xml);
    expect(xml).toContain('<sf:Representante>');
  });

  it('carries RemisionVoluntaria', async () => {
    const cabecera: Cabecera = {
      ...CABECERA,
      RemisionVoluntaria: { FechaFinVeriFactu: '31-12-2026', Incidencia: 'N' },
    };
    const xml = await documento([await altaMinima()], cabecera);

    await esperarValido(xml);
    expect(textoDe(xml, 'sf:FechaFinVeriFactu')).toBe('31-12-2026');
  });

  it('carries RemisionRequerimiento', async () => {
    const cabecera: Cabecera = {
      ...CABECERA,
      RemisionRequerimiento: { RefRequerimiento: 'REQ-000000000001', FinRequerimiento: 'S' },
    };
    const xml = await documento([await altaMinima()], cabecera);

    await esperarValido(xml);
    expect(textoDe(xml, 'sf:RefRequerimiento')).toBe('REQ-000000000001');
  });

  it('rejects the two submission-circumstance blocks together (D-16)', async () => {
    // The XSD accepts this; F3 §3.1.1 does not, because one is for verifiable systems and the
    // other for non-verifiable ones.
    const cabecera: Cabecera = {
      ...CABECERA,
      RemisionVoluntaria: { Incidencia: 'N' },
      RemisionRequerimiento: { RefRequerimiento: 'REQ-1' },
    };
    const registros = [await altaMinima()];

    expect(codigoDe(() => serializarRemision({ cabecera, registros }))).toBe(
      'CABECERA_INCOHERENTE',
    );
  });

  it('confirms the XSD really does accept what F3 forbids', async () => {
    // If this ever starts failing, the AEAT tightened the schema and the check above became
    // redundant. Better to find out from a test than from a rejected submission.
    const xml = (await documento([await altaMinima()])).replace(
      '</sfLR:Cabecera>',
      '<sf:RemisionVoluntaria><sf:Incidencia>N</sf:Incidencia></sf:RemisionVoluntaria>' +
        '<sf:RemisionRequerimiento><sf:RefRequerimiento>REQ-1</sf:RefRequerimiento>' +
        '</sf:RemisionRequerimiento></sfLR:Cabecera>',
    );
    await esperarValido(xml);
  });

  it('omits an empty RemisionVoluntaria instead of emitting it (D-17)', async () => {
    const cabecera: Cabecera = { ...CABECERA, RemisionVoluntaria: {} };
    const xml = await documento([await altaMinima()], cabecera);

    expect(xml).not.toContain('RemisionVoluntaria');
    await esperarValido(xml);
  });

  it('has no IDVersion: that lives once per record', async () => {
    const xml = await documento(await cadenaDe(3));

    expect(xml).not.toContain('<sfLR:IDVersion>');
    expect(todosLosTextosDe(xml, 'sf:IDVersion')).toEqual(['1.0', '1.0', '1.0']);
  });

  it('has no TipoComunicacion: it does not exist in VERI*FACTU', async () => {
    // An SII habit. The equivalent lives per record, as Subsanacion / RechazoPrevio.
    expect(await documento([await altaMinima()])).not.toContain('TipoComunicacion');
  });
});

describe('the batch is a contiguous, ordered segment of one chain', () => {
  it('serialises a real three-record chain', async () => {
    const registros = await cadenaDe(3);
    const xml = documento(registros);

    await esperarValido(xml);
    expect(xml.match(/<sfLR:RegistroFactura>/g)).toHaveLength(3);

    // Record n carries record n-1's digest, and only the first says PrimerRegistro.
    expect(xml.match(/<sf:PrimerRegistro>/g)).toHaveLength(1);
    const huellas = todosLosTextosDe(xml, 'sf:Huella');
    // Two per chained record (previous + own), one for the first.
    expect(huellas).toEqual([
      registros[0]?.eslabon.huella,
      registros[0]?.eslabon.huella,
      registros[1]?.eslabon.huella,
      registros[1]?.eslabon.huella,
      registros[2]?.eslabon.huella,
    ]);
  });

  it('mixes altas and anulaciones, which F3 §3.1.2 allows explicitly', async () => {
    const alta = await altaPrevia();
    const anulacion = await cadena('2024-01-01T18:30:00Z').anulacion({
      IDEmisorFacturaAnulada: '89890001K',
      NumSerieFacturaAnulada: '12345679/G34',
      FechaExpedicionFacturaAnulada: '01-01-2024',
      previous: alta,
    });

    const xml = documento([
      { eslabon: alta, datos: (await altaMinima()).datos },
      { eslabon: anulacion, datos: { SistemaInformatico: SISTEMA } },
    ]);

    await esperarValido(xml);
    expect(xml).toContain('<sf:RegistroAlta>');
    expect(xml).toContain('<sf:RegistroAnulacion>');
  });

  it('chains an alta onto an anulación, using the Anulada fields as its identity', async () => {
    const anulacion = await anulacionMinima();
    const alta = await cadena('2024-01-01T18:40:00Z').alta({
      IDEmisorFactura: '89890001K',
      NumSerieFactura: 'DESPUES/1',
      FechaExpedicionFactura: '01-01-2024',
      TipoFactura: 'F1',
      CuotaTotal: '12.35',
      ImporteTotal: '123.45',
      previous: anulacion.eslabon,
    });

    const xml = documento([anulacion, { eslabon: alta, datos: (await altaMinima()).datos }]);

    await esperarValido(xml);
    // Inside RegistroAnterior the previous record is named without the `Anulada` suffixes.
    expect(xml).toContain(
      '<sf:RegistroAnterior><sf:IDEmisorFactura>89890001K</sf:IDEmisorFactura>' +
        '<sf:NumSerieFactura>12345679/G34</sf:NumSerieFactura>',
    );
  });

  it('rejects records given out of order', async () => {
    const [a, b, c] = await cadenaDe(3);
    const desordenado = [a, c, b] as RegistroFactura[];

    expect(codigoDe(() => documento(desordenado))).toBe('LOTE_NO_CONTIGUO');
  });

  it('rejects a gap in the middle', async () => {
    const [a, , c] = await cadenaDe(3);

    expect(codigoDe(() => documento([a, c] as RegistroFactura[]))).toBe('LOTE_NO_CONTIGUO');
  });

  it('names the index and both digests when the segment breaks', async () => {
    const [a, , c] = await cadenaDe(3);
    try {
      documento([a, c] as RegistroFactura[]);
      expect.unreachable('should have thrown');
    } catch (error) {
      const e = error as VerifactuXmlError;
      expect(e.message).toContain('Registro 1 del lote');
      expect(e.message).toContain(a?.eslabon.huella ?? '');
      expect(e.message).toContain(c?.eslabon.fields.Huella ?? '');
    }
  });

  it('rejects a second PrimerRegistro in the middle', async () => {
    const registros = await cadenaDe(2);
    const otraCadena = await altaMinima({ NumSerieFactura: 'OTRA/1' });

    expect(codigoDe(() => documento([registros[0] as RegistroFactura, otraCadena]))).toBe(
      'LOTE_NO_CONTIGUO',
    );
  });

  it('explains that a restart means two chains got mixed', async () => {
    const registros = await cadenaDe(2);
    const otraCadena = await altaMinima({ NumSerieFactura: 'OTRA/1' });
    try {
      documento([registros[0] as RegistroFactura, otraCadena]);
      expect.unreachable('should have thrown');
    } catch (error) {
      expect((error as VerifactuXmlError).causaProbable).toContain('posición 0');
    }
  });

  it('accepts a first record that points outside the batch', async () => {
    // A batch is a segment, not a whole chain: its first record legitimately chains onto one
    // that was sent earlier and is not in this message.
    const registros = await cadenaDe(3);
    const xml = documento(registros.slice(1));

    await esperarValido(xml);
    expect(xml).not.toContain('<sf:PrimerRegistro>');
  });

  it('rejects a predecessor reference that does not match the previous record', async () => {
    const [a, b] = await cadenaDe(2);
    const manipulado = {
      ...(b as RegistroFactura),
      eslabon: {
        ...(b as RegistroFactura).eslabon,
        registroAnterior: {
          ...((b as RegistroFactura).eslabon.registroAnterior ?? {
            IDEmisorFactura: '',
            NumSerieFactura: '',
            FechaExpedicionFactura: '',
            Huella: '',
          }),
          NumSerieFactura: 'OTRA-SERIE',
        },
      },
    } as RegistroFactura;

    expect(codigoDe(() => documento([a as RegistroFactura, manipulado]))).toBe('LOTE_NO_CONTIGUO');
  });

  it('rejects a link that carries the previous digest but not its identity', async () => {
    const [a, b] = await cadenaDe(2);
    const manipulado = {
      ...(b as RegistroFactura),
      eslabon: { ...(b as RegistroFactura).eslabon, registroAnterior: null },
    } as RegistroFactura;

    expect(codigoDe(() => documento([a as RegistroFactura, manipulado]))).toBe('LOTE_NO_CONTIGUO');
  });
});

describe('every record belongs to the obliged party in the header', () => {
  it('rejects a record issued by someone else', async () => {
    // F3 §3.1.3.1: IDEmisorFactura must equal Cabecera/ObligadoEmision/NIF. A chain may change
    // NIF over time (§4.3); a batch may not — it splits at that point.
    const otro = await altaMinima({ IDEmisorFactura: 'B72877814' });

    expect(codigoDe(() => documento([otro]))).toBe('EMISOR_DISTINTO_DEL_OBLIGADO');
  });

  it('rejects an anulación issued by someone else', async () => {
    const otra = await anulacionMinima({ IDEmisorFacturaAnulada: 'B72877814' });

    expect(codigoDe(() => documento([otra]))).toBe('EMISOR_DISTINTO_DEL_OBLIGADO');
  });

  it('says which record, and suggests splitting the batch', async () => {
    const registros = [await altaMinima(), await altaMinima({ IDEmisorFactura: 'B72877814' })];
    try {
      documento(registros);
      expect.unreachable('should have thrown');
    } catch (error) {
      const e = error as VerifactuXmlError;
      expect(e.message).toContain('Registro 1 del lote');
      expect(e.message).toContain('B72877814');
      expect(e.accionSugerida).toContain('otro');
    }
  });

  it('accepts the batch when the header declares that same NIF', async () => {
    const cabecera: Cabecera = { ObligadoEmision: { NombreRazon: 'OTRA SL', NIF: 'B72877814' } };
    const registro = await altaMinima({ IDEmisorFactura: 'B72877814' });

    await esperarValido(await documento([registro], cabecera));
  });
});

describe('batch size', () => {
  it('rejects an empty batch', async () => {
    expect(codigoDe(() => documento([]))).toBe('CARDINALIDAD_INVALIDA');
  });

  it('accepts the 1000-record maximum', async () => {
    const registros = await cadenaDe(1000);
    const xml = documento(registros);

    expect(xml.match(/<sfLR:RegistroFactura>/g)).toHaveLength(1000);
    await esperarValido(xml);
  }, 60_000);

  it('rejects 1001', async () => {
    const registros = await cadenaDe(1001);
    expect(codigoDe(() => documento(registros))).toBe('CARDINALIDAD_INVALIDA');
  }, 60_000);

  it('validates the batch before writing anything', async () => {
    // A rejected batch must not leave half a document behind for someone to send by accident.
    const registros = await cadenaDe(1001);
    try {
      documento(registros);
      expect.unreachable('should have thrown');
    } catch (error) {
      expect((error as VerifactuXmlError).code).toBe('CARDINALIDAD_INVALIDA');
    }
  }, 60_000);
});
